pipeline:
  tests:
    image: node:7-alpine
    when:
      event: push
    commands:
      - yarn
      - yarn test
      - yarn run lint
      - yarn run build

  docker:
    image: plugins/docker
    when:
      branch:
        - prod
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego-webapp
    tags:
      - latest
      - ${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
    build_args:
      - API_URL=${API_URL}
      - WS_URL=${WS_URL}
      - BASE_URL=${BASE_URL}
      - CAPTCHA_KEY=${CAPTCHA_KEY}

  deploy:
    image: quay.io/ipedrazas/drone-helm
    when:
      branch:
        - prod
    skip_tls_verify: true
    chart: ./charts/lego-webapp
    release: lego-webapp-prod
    namespace: lego-prod
    values: webapp.image.tag=${DRONE_BRANCH}-${DRONE_COMMIT_SHA:0:7}
