pipeline:
  tests:
    image: node:7-alpine
    when:
      event: push
    commands:
      - yarn
      - yarn test
      - yarn run lint
      - yarn run build

  docker:
    image: plugins/docker
    when:
      event: tag
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego-webapp
    tags:
      - latest
      - ${DRONE_TAG##v}
    build_args:
      - API_URL=${API_URL}
      - WS_URL=${WS_URL}
      - BASE_URL=${BASE_URL}
      - CAPTCHA_KEY=${CAPTCHA_KEY}
