pipeline:
  tests:
    image: node:7-alpine
    when:
      event: push
    commands:
      - yarn
      - yarn test
      - yarn run lint
      - yarn run build

  docker:
    image: plugins/docker
    when:
      event: tag
    registry: https://registry.abakus.no
    repo: registry.abakus.no/webkom/lego/lego-webapp
    tags:
      - ${DRONE_TAG##v}
      - latest
