tasks:
 - npm install
 - npm test
 - npm run lint

deploy_tasks:
 - npm install
 - npm install forever
 - npm run bundle
 - PORT=8000 ./node_modules/.bin/forever start node_modules/.bin/6to5-node server.js

coverage:
  path: coverage/cobertura-coverage.xml
  parser: cobertura

deployment:
  image: frigg/frigg-test-base
